
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "id numComandos : Comandos ComandoComandos : Comando\n    Comando : Ler\n           |  Escrever\n           |  Despejar\n           |  Atrib\n           |  Exp\n    Exp : Exp '+' TermoExp : Exp '-' TermoExp : TermoTermo : Termo '*' FactorTermo : Termo '/' FactorTermo : FactorFactor : idFactor : numFactor : '(' Exp ')' Ler : '?' idEscrever : '!' idDespejar : '!' '!'Atrib : id '=' Exp"
    
_lr_action_items = {'?':([0,1,2,3,4,5,6,7,9,11,12,13,15,18,20,21,25,26,27,28,29,30,31,],[8,8,-2,-3,-4,-5,-6,-7,-14,-10,-13,-15,-1,-17,-19,-18,-14,-8,-9,-20,-11,-12,-16,]),'!':([0,1,2,3,4,5,6,7,9,10,11,12,13,15,18,20,21,25,26,27,28,29,30,31,],[10,10,-2,-3,-4,-5,-6,-7,-14,20,-10,-13,-15,-1,-17,-19,-18,-14,-8,-9,-20,-11,-12,-16,]),'id':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,],[9,9,-2,-3,-4,-5,-6,-7,18,-14,21,-10,-13,-15,25,-1,25,25,-17,25,-19,-18,25,25,-14,-8,-9,-20,-11,-12,-16,]),'num':([0,1,2,3,4,5,6,7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,],[13,13,-2,-3,-4,-5,-6,-7,-14,-10,-13,-15,13,-1,13,13,-17,13,-19,-18,13,13,-14,-8,-9,-20,-11,-12,-16,]),'(':([0,1,2,3,4,5,6,7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,],[14,14,-2,-3,-4,-5,-6,-7,-14,-10,-13,-15,14,-1,14,14,-17,14,-19,-18,14,14,-14,-8,-9,-20,-11,-12,-16,]),'$end':([1,2,3,4,5,6,7,9,11,12,13,15,18,20,21,25,26,27,28,29,30,31,],[0,-2,-3,-4,-5,-6,-7,-14,-10,-13,-15,-1,-17,-19,-18,-14,-8,-9,-20,-11,-12,-16,]),'+':([7,9,11,12,13,24,25,26,27,28,29,30,31,],[16,-14,-10,-13,-15,16,-14,-8,-9,16,-11,-12,-16,]),'-':([7,9,11,12,13,24,25,26,27,28,29,30,31,],[17,-14,-10,-13,-15,17,-14,-8,-9,17,-11,-12,-16,]),'=':([9,],[19,]),'*':([9,11,12,13,25,26,27,29,30,31,],[-14,22,-13,-15,-14,22,22,-11,-12,-16,]),'/':([9,11,12,13,25,26,27,29,30,31,],[-14,23,-13,-15,-14,23,23,-11,-12,-16,]),')':([11,12,13,24,25,26,27,29,30,31,],[-10,-13,-15,31,-14,-8,-9,-11,-12,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comandos':([0,],[1,]),'Comando':([0,1,],[2,15,]),'Ler':([0,1,],[3,3,]),'Escrever':([0,1,],[4,4,]),'Despejar':([0,1,],[5,5,]),'Atrib':([0,1,],[6,6,]),'Exp':([0,1,14,19,],[7,7,24,28,]),'Termo':([0,1,14,16,17,19,],[11,11,11,26,27,11,]),'Factor':([0,1,14,16,17,19,22,23,],[12,12,12,12,12,12,29,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comandos","S'",1,None,None,None),
  ('Comandos -> Comandos Comando','Comandos',2,'p_Comandos','gerador_yacc.py',8),
  ('Comandos -> Comando','Comandos',1,'p_Comando_unico','gerador_yacc.py',12),
  ('Comando -> Ler','Comando',1,'p_Comando','gerador_yacc.py',17),
  ('Comando -> Escrever','Comando',1,'p_Comando','gerador_yacc.py',18),
  ('Comando -> Despejar','Comando',1,'p_Comando','gerador_yacc.py',19),
  ('Comando -> Atrib','Comando',1,'p_Comando','gerador_yacc.py',20),
  ('Comando -> Exp','Comando',1,'p_Comando','gerador_yacc.py',21),
  ('Exp -> Exp + Termo','Exp',3,'p_Exp_add','gerador_yacc.py',26),
  ('Exp -> Exp - Termo','Exp',3,'p_Exp_sub','gerador_yacc.py',30),
  ('Exp -> Termo','Exp',1,'p_Exp_termo','gerador_yacc.py',34),
  ('Termo -> Termo * Factor','Termo',3,'p_Termo_mul','gerador_yacc.py',38),
  ('Termo -> Termo / Factor','Termo',3,'p_Termo_div','gerador_yacc.py',42),
  ('Termo -> Factor','Termo',1,'p_Termo_factor','gerador_yacc.py',50),
  ('Factor -> id','Factor',1,'p_Factor_id','gerador_yacc.py',54),
  ('Factor -> num','Factor',1,'p_Factor_num','gerador_yacc.py',58),
  ('Factor -> ( Exp )','Factor',3,'p_Factor_group','gerador_yacc.py',62),
  ('Ler -> ? id','Ler',2,'p_Ler','gerador_yacc.py',67),
  ('Escrever -> ! id','Escrever',2,'p_Escrever','gerador_yacc.py',72),
  ('Despejar -> ! !','Despejar',2,'p_Despejar','gerador_yacc.py',76),
  ('Atrib -> id = Exp','Atrib',3,'p_Atrib','gerador_yacc.py',81),
]
